### ISSUE TITLE
Accented characters and internal hyperlink

### ISSUE THREAD

**Issue by GittyBob** [macmarrum/freeplane-PackAndGoGo#2]
Hi,

I discovered 2 others bugs:

- Accented characters  are converted to another encoding. Ex: "Confidentialité" becomes "Confidentialit�"
- The hyperlinks to internal node of the mindmap are replaced with a wrong link. eg:  in the MYMAP.mm source, the initial file contains LINK="#ID_531479717" but after using PackAndGoGo it is replaced by  LINK="MYMAP-files/parent-directory-name/" 

Thanks again for your great work and your very quick answering !

**Comment by macmarrum** [comment]
@GittyBob 

Thanks for the bug report.

I understand the second point, but I'm struggling to get the first one.
Could you please describe in more detail where the accented characters are located or even better, attach a sample mind map?

**Comment by macmarrum** [comment]
@GittyBob 
Second point is fixed. Once you get a chance to describe the first one in more detail, please open a new issue.
