### ISSUE TITLE
Issue with accented characters 

### ISSUE THREAD

**Issue by GittyBob** [macmarrum/freeplane-PackAndGoGo#4]
Hi,

As mentioned previously packandgogo change the character encoding. The original file uses the UTF-8 encoding but the packed file uses ANSI encoding

I join a zip file with the original file and the packed one:

[TEST-packandgogo.zip](https://github.com/macmarrum/freeplane-PackAndGoGo/files/13120226/TEST-packandgogo.zip)

Freeplane displays the original file correctly, but the packed one displays wrong accented characters.
If you open the .mm file in a text editor that autodetect encoding, you will see that the original file is UTF-8 encoded, and the packed one ANSI encoded.

Again, thanks a lot for your great support ! :)

**Comment by macmarrum** [comment]
Fixed in https://github.com/macmarrum/freeplane-PackAndGoGo/releases/tag/v2024.3.19
